apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '8080'
    prometheus.io/path: /q/metrics
    prometheus.io/scheme: http
    prometheus.io/scrape: 'true'
  name: quarked     
  namespace: kevin-dubois-dev
  labels:
    app.kubernetes.io/component: quarked
    app.kubernetes.io/instance: quarked
    app.kubernetes.io/name: quarked
    app.kubernetes.io/version: latest
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-version: latest
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: '1'
        autoscaling.knative.dev/window: 20s
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: quarked
        app.kubernetes.io/instance: quarked
        app.kubernetes.io/name: quarked
        app.kubernetes.io/version: latest
        app.openshift.io/runtime: quarkus
        app.openshift.io/runtime-version: latest
    spec:
      containerConcurrency: 1
      containers:
        - image: quay.io/kevindubois/quarked:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 0
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: quarked
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 0
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 10
  traffic:
    - latestRevision: true
      percent: 100